### ISSUE TITLE
Cookies broken after 1.9.0

### ISSUE THREAD

**Issue by lsgunth** [django-webtest/django-webtest#69]
Hi, 

After attempting to upgrade to 1.9.1 I found my tests that use app.set_cookie no longer work. The exact same code worked in 1.8.0 and earlier. I narrowed down the problem to commit 9eb0fef9. It seems setting HTTP_HOST means none of my cookies get forwarded to Django proper (this is Django 1.9.12) . Commenting out that line, or even changing it to HTTPS_HOST seems to fix the issue.

Thanks,

Logan

**Comment by gawel** [comment]
The real problem is in webtest where localhost is hard coded https://github.com/Pylons/webtest/blob/master/webtest/app.py#L241

**Comment by gawel** [comment]
Webtest 2.0.27 should fix the problem.

**Comment by lsgunth** [comment]
Hmm, I see. But the problem still isn't fixed. If I add the following line before setting the cookie, then it works, but that seems like it shouldn't be necessary.

self.app.extra_environ['HTTP_HOST'] = 'testserver'

Thanks,

Logan
